export const API_VERSION = 'v1';
export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

export const ROLES = {
  CANDIDATE: 'CANDIDATE',
  EMPLOYER_ADMIN: 'EMPLOYER_ADMIN',
  EMPLOYER_RECRUITER: 'EMPLOYER_RECRUITER',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  PLATFORM_OPERATOR: 'PLATFORM_OPERATOR',
} as const;
