// ATS characteristics of each resume template. Scoring uses these
// profiles rather than inspecting rendered HTML, because every template
// in this app is a known single-column React layout.

const TEMPLATE_PROFILES = {
  "ats-minimal": {
    name: "ATS Minimal",
    hasPhoto: false,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 100,
    typography: 98,
    sectionStructure: 100,
    machineReadability: 98,
    photoUsage: "N/A",
    atsCompatibility: 97,
    notes: [],
  },
  "ats-classic": {
    name: "ATS Classic",
    hasPhoto: false,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 100,
    typography: 96,
    sectionStructure: 100,
    machineReadability: 97,
    photoUsage: "N/A",
    atsCompatibility: 96,
    notes: [],
  },
  "ats-professional": {
    name: "ATS Professional",
    hasPhoto: false,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 100,
    typography: 97,
    sectionStructure: 100,
    machineReadability: 97,
    photoUsage: "N/A",
    atsCompatibility: 96,
    notes: [],
  },
  "ats-executive": {
    name: "ATS Executive",
    hasPhoto: false,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 100,
    typography: 95,
    sectionStructure: 98,
    machineReadability: 96,
    photoUsage: "N/A",
    atsCompatibility: 95,
    notes: ["Uses 'Professional Summary' and 'Professional Experience' headings, which remain ATS-standard."],
  },
  "ats-modern": {
    name: "ATS Modern",
    hasPhoto: false,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 100,
    typography: 95,
    sectionStructure: 100,
    machineReadability: 96,
    photoUsage: "N/A",
    atsCompatibility: 95,
    notes: [],
  },
  "photo-professional": {
    name: "Photo Professional",
    hasPhoto: true,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 98,
    typography: 95,
    sectionStructure: 98,
    machineReadability: 92,
    photoUsage: "Optional decorative photo. No resume text is stored in the image.",
    atsCompatibility: 92,
    notes: ["Optional photo does not contain contact or experience text."],
  },
  "photo-executive": {
    name: "Photo Executive",
    hasPhoto: true,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 98,
    typography: 94,
    sectionStructure: 98,
    machineReadability: 91,
    photoUsage: "Optional decorative photo. No resume text is stored in the image.",
    atsCompatibility: 91,
    notes: ["Optional photo does not contain contact or experience text."],
  },
  "photo-modern": {
    name: "Photo Modern",
    hasPhoto: true,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 97,
    typography: 94,
    sectionStructure: 97,
    machineReadability: 90,
    photoUsage: "Optional decorative photo. No resume text is stored in the image.",
    atsCompatibility: 90,
    notes: ["Accent rule is decorative CSS, not a graphic chart."],
  },
  "photo-corporate": {
    name: "Photo Corporate",
    hasPhoto: true,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 98,
    typography: 95,
    sectionStructure: 98,
    machineReadability: 91,
    photoUsage: "Optional decorative photo. No resume text is stored in the image.",
    atsCompatibility: 91,
    notes: [],
  },
  "photo-elegant": {
    name: "Photo Elegant",
    hasPhoto: true,
    singleColumn: true,
    usesTablesForLayout: false,
    usesSkillBars: false,
    usesCharts: false,
    importantTextInImages: false,
    standardHeadings: true,
    readableTypography: true,
    highContrast: true,
    contactAsText: true,
    experienceAsText: true,
    educationAsText: true,
    skillsAsText: true,
    predictableStructure: true,
    readingOrder: 97,
    typography: 93,
    sectionStructure: 97,
    machineReadability: 90,
    photoUsage: "Optional decorative photo. No resume text is stored in the image.",
    atsCompatibility: 90,
    notes: ["Serif headings remain selectable HTML text."],
  },
};

const DEFAULT_PROFILE = {
  name: "Unknown template",
  hasPhoto: false,
  singleColumn: true,
  usesTablesForLayout: false,
  usesSkillBars: false,
  usesCharts: false,
  importantTextInImages: false,
  standardHeadings: true,
  readableTypography: true,
  highContrast: true,
  contactAsText: true,
  experienceAsText: true,
  educationAsText: true,
  skillsAsText: true,
  predictableStructure: true,
  readingOrder: 90,
  typography: 90,
  sectionStructure: 90,
  machineReadability: 88,
  photoUsage: "Unknown",
  atsCompatibility: 88,
  notes: ["Template is not in the known ATS profile list; scored conservatively."],
};

function getTemplateProfile(templateId) {
  return TEMPLATE_PROFILES[templateId] || { ...DEFAULT_PROFILE, name: templateId || "Unknown template" };
}

module.exports = { TEMPLATE_PROFILES, getTemplateProfile };
