NODE_ENV: production
GCP_PROJECT_ID: careerbridge-f7b72
GCS_BUCKET: srsbbucket
GCP_REGION: asia-south1
FIREBASE_PROJECT_ID: careerbridge-f7b72
AUTH_DEV_OTP: "false"
DATABASE_USER: careerbridge_app
DATABASE_NAME: careerbridge_dev
DATABASE_HOST: /cloudsql/careerbridge-f7b72:asia-south1:careerbridge-dev-db
WEB_ORIGIN: "http://localhost:3000,https://www.srsbcareerbridge.com"
