export const DEGREE_OPTIONS = [
  "10th",
  "12th",
  "ITI",
  "Diploma",
  "BE",
  "B.Tech",
  "B.Sc",
  "B.Com",
  "B.A",
  "BBA",
  "BCA",
  "B.Pharm",
  "B.Arch",
  "B.Des",
  "B.Ed",
  "LLB",
  "MBBS",
  "BDS",
  "ME",
  "M.Tech",
  "M.Sc",
  "M.Com",
  "M.A",
  "MBA",
  "MCA",
  "M.Pharm",
  "M.Arch",
  "LLM",
  "MD",
  "MS",
  "PhD",
  "Other",
];

export const COLLEGE_OPTIONS = [
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Guwahati",
  "Indian Institute of Technology Hyderabad",
  "Indian Institute of Science Bangalore",
  "National Institute of Technology Trichy",
  "National Institute of Technology Surathkal",
  "National Institute of Technology Warangal",
  "National Institute of Technology Calicut",
  "National Institute of Technology Rourkela",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "Anna University",
  "College of Engineering Guindy",
  "PSG College of Technology",
  "Thiagarajar College of Engineering",
  "SSN College of Engineering",
  "SRM Institute of Science and Technology",
  "Vellore Institute of Technology",
  "Amrita Vishwa Vidyapeetham",
  "SASTRA University",
  "Sathyabama University",
  "Hindustan Institute of Technology and Science",
  "Loyola College Chennai",
  "Madras Christian College",
  "Stella Maris College",
  "University of Madras",
  "University of Delhi",
  "St Stephen's College",
  "Hindu College Delhi",
  "Miranda House",
  "Jawaharlal Nehru University",
  "Jamia Millia Islamia",
  "Banaras Hindu University",
  "Aligarh Muslim University",
  "University of Mumbai",
  "St Xavier's College Mumbai",
  "SP Jain Institute of Management",
  "NMIMS Mumbai",
  "Savitribai Phule Pune University",
  "College of Engineering Pune",
  "Fergusson College",
  "Osmania University",
  "JNTU Hyderabad",
  "BITS Pilani",
  "BITS Hyderabad",
  "Manipal Institute of Technology",
  "Christ University",
  "Jadavpur University",
  "Calcutta University",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Kozhikode",
  "IIM Lucknow",
  "XLRI Jamshedpur",
  "ISB Hyderabad",
  "Chandigarh University",
  "Lovely Professional University",
  "Amity University",
  "Shiv Nadar University",
  "Ashoka University",
  "Coimbatore Institute of Technology",
  "Kumaraguru College of Technology",
  "Kongu Engineering College",
  "Government College of Technology Coimbatore",
  "Madurai Kamaraj University",
  "Bharathiar University",
  "Bharathidasan University",
  "Annamalai University",
  "Other",
];

export const SKILL_OPTIONS = [
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "C",
  "C++",
  "C#",
  "Go",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "SQL",
  "HTML",
  "CSS",
  "React",
  "Next.js",
  "Angular",
  "Vue",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Spring Boot",
  "Android",
  "iOS",
  "React Native",
  "Flutter",
  "Git",
  "GitHub",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Linux",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Redis",
  "GraphQL",
  "REST APIs",
  "Machine Learning",
  "Data Analysis",
  "Power BI",
  "Tableau",
  "Excel",
  "MS Excel",
  "MS Word",
  "MS PowerPoint",
  "Google Workspace",
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "UI Design",
  "UX Design",
  "Video Editing",
  "Canva",
  "Communication",
  "English",
  "Tamil",
  "Hindi",
  "Customer Service",
  "Sales",
  "Negotiation",
  "Teamwork",
  "Leadership",
  "Problem Solving",
  "Time Management",
  "Presentation",
  "Public Speaking",
  "Data Entry",
  "Typing",
  "Tally",
  "Accounting",
  "GST",
  "Bookkeeping",
  "HR",
  "Recruitment",
  "Digital Marketing",
  "SEO",
  "Social Media Marketing",
  "Content Writing",
  "Copywriting",
  "Email Marketing",
  "Retail",
  "Cash Handling",
  "Inventory Management",
  "Logistics",
  "Warehouse",
  "Driving",
  "Delivery",
  "Electrician",
  "Plumbing",
  "Carpentry",
  "Welding",
  "Machine Operation",
  "Quality Control",
  "Safety",
  "First Aid",
  "Nursing",
  "Teaching",
  "Tutoring",
  "Event Management",
  "Hospitality",
  "Cooking",
  "Housekeeping",
];
